/**
 * default_1476154119719
 * 覆盖全，秒响应，超稳定！验证姓名+身份证号+银行卡号+手机号是否一致。实时联网核查结果！---捷安数据
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.yhb.common.bankcardvertify.api;


import com.google.gson.reflect.TypeToken;
import com.squareup.okhttp.Call;
import com.yhb.common.bankcardvertify.wxlink.*;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DefaultApi {
    private ApiClient apiClient;

    public DefaultApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DefaultApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for cardFourTransfer */
    private Call cardFourTransferCall(String CERT_ID, String CERT_NAME, String CARD_ID, String MP, String appkey, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // verify the required parameter 'CERT_ID' is set
        if (CERT_ID == null) {
            throw new ApiException("Missing the required parameter 'CERT_ID' when calling cardFourTransfer(Async)");
        }
        
        // verify the required parameter 'CERT_NAME' is set
        if (CERT_NAME == null) {
            throw new ApiException("Missing the required parameter 'CERT_NAME' when calling cardFourTransfer(Async)");
        }
        
        // verify the required parameter 'CARD_ID' is set
        if (CARD_ID == null) {
            throw new ApiException("Missing the required parameter 'CARD_ID' when calling cardFourTransfer(Async)");
        }
        
        // verify the required parameter 'MP' is set
        if (MP == null) {
            throw new ApiException("Missing the required parameter 'MP' when calling cardFourTransfer(Async)");
        }
        
        // verify the required parameter 'appkey' is set
        if (appkey == null) {
            throw new ApiException("Missing the required parameter 'appkey' when calling cardFourTransfer(Async)");
        }
        

        // create path and map variables
        String localVarPath = "/Card4Verify/CardFourTransfer".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (CERT_ID != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "CERT_ID", CERT_ID));
        if (CERT_NAME != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "CERT_NAME", CERT_NAME));
        if (CARD_ID != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "CARD_ID", CARD_ID));
        if (MP != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "MP", MP));
        if (appkey != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("", "appkey", appkey));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "text/plain"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    /**
     * CARD4 姓名+身份证+银行卡号+手机号 用于银行卡四要素认证
     * CARD4 姓名+身份证+银行卡号+手机号 用于银行卡四要素认证
     * @param CERT_ID 身份证号 (required)
     * @param CERT_NAME 姓名 (required)
     * @param CARD_ID 银行卡号 (required)
     * @param MP 手机号 (required)
     * @param appkey 万象平台提供的appkey (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public String cardFourTransfer(String CERT_ID, String CERT_NAME, String CARD_ID, String MP, String appkey) throws ApiException {
        ApiResponse<String> resp = cardFourTransferWithHttpInfo(CERT_ID, CERT_NAME, CARD_ID, MP, appkey);
        return resp.getData();
    }

    /**
     * CARD4 姓名+身份证+银行卡号+手机号 用于银行卡四要素认证
     * CARD4 姓名+身份证+银行卡号+手机号 用于银行卡四要素认证
     * @param CERT_ID 身份证号 (required)
     * @param CERT_NAME 姓名 (required)
     * @param CARD_ID 银行卡号 (required)
     * @param MP 手机号 (required)
     * @param appkey 万象平台提供的appkey (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<String> cardFourTransferWithHttpInfo(String CERT_ID, String CERT_NAME, String CARD_ID, String MP, String appkey) throws ApiException {
        Call call = cardFourTransferCall(CERT_ID, CERT_NAME, CARD_ID, MP, appkey, null, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * CARD4 姓名+身份证+银行卡号+手机号 用于银行卡四要素认证 (asynchronously)
     * CARD4 姓名+身份证+银行卡号+手机号 用于银行卡四要素认证
     * @param CERT_ID 身份证号 (required)
     * @param CERT_NAME 姓名 (required)
     * @param CARD_ID 银行卡号 (required)
     * @param MP 手机号 (required)
     * @param appkey 万象平台提供的appkey (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public Call cardFourTransferAsync(String CERT_ID, String CERT_NAME, String CARD_ID, String MP, String appkey, final ApiCallback<String> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        Call call = cardFourTransferCall(CERT_ID, CERT_NAME, CARD_ID, MP, appkey, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
